app:
  jwt:
    secret: DaeguGreenArtAcademyClass502ForJavaSpringBootFighting
    header-scheme-name: authorization
    token-type: Bearer
    access-token-expiry: 7200000
    refresh-token-expiry: 1296000000 # 대략 15일

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/greengram3
    username: root
    password: green502

mybatis:
  mapper-locations: mappers/**/*.xml

springdoc:
  swagger-ui:
    path: /swagger.html

server:
  port: 8082

